import './users/user.routes.js'
import './profiles/profile.routes.js'
import './posts/post.routes.js'
import './comments/comment.routes.js'
import './likes/like.routes.js'
import './friends/friend.routes.js'
